### ISSUE TITLE
Change username within a session

### ISSUE THREAD

**Issue by ghdulrich** [agower/GeneHive#6]
The only way I can alter the username within an R session is to exit and export HIVE_USERNAME="myuser". I tried Sys.setenv("HIVE_USERNAME"="dulrich") in the session and that didnt work.

**Comment by ghdulrich** [comment]
Ah -- got it.
`options(GeneHive.username ='myuser'`

**Comment by agower** [comment]
Yes, this is because the R package only reads the environment variables once, on package startup, via the function `.onLoad()` in `[hooks.R](https://github.com/agower/GeneHive/blob/master/R/hooks.R)`.  As you mentioned, this function then stores these values in the corresponding elements of the global options (e.g., `GeneHive.username`).  I will clarify the documentation to make this more explicit to the user.
